apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - helm-repository.yaml
  - postgres
  - rabbitmq
  - celery-worker
  - django
  - celery-beat

images:
  - name: ghcr.io/apoorva64/ffmpeg-scheduler/main
    newName: ghcr.io/apoorva64/ffmpeg-scheduler/main
    newTag: 1.0.0