apiVersion: apps/v1
kind: Deployment
metadata:
  name: celery-beat
  namespace: ffmpeg-scheduler
spec:
  selector:
    matchLabels:
      app: celery-beat
  replicas: 1
  template:
    metadata:
      labels:
        app: celery-beat
    spec:
      containers:
      - name: celery
        image: git.ozeliurs.com/youtube-analyser/backend:v1.0.1
        command: ["deployment/entry_point_celery.sh"]
        env:
          - name: POSTGRES_HOST
            value: "postgresql"
          - name: POSTGRES_USER
            value: "postgres"
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: postgresql
                key: postgres-password
          - name: POSTGRES_DB
            value: "youtube-analyser"
          - name: RABBITMQ_HOST
            value: "rabbitmq"
          - name: RABBITMQ_USER
            value: "youtube-analyser"
          - name: RABBITMQ_PORT
            value: "5672"
          - name: RABBITMQ_PASSWORD
            valueFrom:
              secretKeyRef:
                name: rabbitmq
                key: rabbitmq-password
          - name: RABBITMQ_VHOST
            value: "/"

