apiVersion: apps/v1
kind: Deployment
metadata:
  name: django
  namespace: ffmpeg-scheduler
spec:
  selector:
    matchLabels:
      app: django
  replicas: 1
  template:
    metadata:
      labels:
        app: django
    spec:
      containers:
        - name: celery
          image: ghcr.io/apoorva64/ffmpeg-scheduler:latest
          command: [ "deployment/entry_point.sh" ]
          env:
            - name: POSTGRES_HOST
              value: "postgresql"
            - name: POSTGRES_USER
              value: "postgres"
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgresql
                  key: postgres-password
            - name: POSTGRES_DB
              value: "postgres"
            - name: RABBITMQ_HOST
              value: "rabbitmq"
            - name: RABBITMQ_USER
              value: "youtube-analyser"
            - name: RABBITMQ_PORT
              value: "5672"
            - name: RABBITMQ_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: rabbitmq
                  key: rabbitmq-password
            - name: RABBITMQ_VHOST
              value: "/"
            - name: MINIO_ENDPOINT
              valueFrom:
                secretKeyRef:
                  name: minio-auth
                  key: MINIO_ENDPOINT
            - name: MINIO_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: minio-auth
                  key: MINIO_ACCESS_KEY

            - name: MINIO_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: minio-auth
                  key: MINIO_SECRET_KEY
            - name: MINIO_SECURE
              valueFrom:
                secretKeyRef:
                  name: minio-auth
                  key: MINIO_SECURE
