apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: postgresql
  namespace: ffmpeg-scheduler
spec:
  interval: 60m
  chart:
    spec:
      chart: postgresql
      version: "*"
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: youtube-analyser
      interval: 24h
  values:
    storageClass: longhorn-single-replica
