name: Docker Image Build and Push

on:
  push:
    paths:
      - 'requirements.txt'
    branches:
      - 'master'

jobs:
  base-image-docker:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          platforms: linux/arm64,linux/amd64
          push: true
          tags: ghcr.io/apoorva64/ffmpeg-scheduler/base:latest
          file: ./base_image/Dockerfile